version: '3'
services:
  todotests:
    build: docker/todo-app/tests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    restart: always

  todofront:
    build: docker/todo-app/front-end
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    restart: always
    
  todoback:
    build: docker/todo-app/back-end
    ports:
      - 3001:3001
    restart: always